### ISSUE TITLE
test

### ISSUE THREAD

**Issue by rfranzke** [gardener-attic/bot-test-repo-1#15]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

/kind/bug
/area/networking
/priority/critical
/component/gardener
/platform/aws

/lgtm
/assign @vlerenc

**Comment by rfranzke** [comment]
/kind/enhancement
/needs/rebase

**Comment by vlerenc** [comment]
/remove kind enhancement
oder auch
/drop rebase
und tausend andere Kombinationen ;-)

Siehe https://github.wdf.sap.corp/kubernetes/github-botmanager/commit/c4c84c84648518f76d3f7d20b6271ebf0e148691

**Comment by vlerenc** [comment]
/kind/enhancement
/needs/rebase

**Comment by vlerenc** [comment]
/remove kind enhancement
oder auch
/drop rebase
und tausend andere Kombinationen ;-)

Siehe https://github.wdf.sap.corp/kubernetes/github-botmanager/commit/c4c84c84648518f76d3f7d20b6271ebf0e148691
