### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by rfranzke** [gardener-attic/bot-test-repo-1#21]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

/kind enhancement
/lgtm
/assign
/cc @vlerenc 
/hold

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Command "/cc vlerenc " either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Command "/hold" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Command "/cc vlerenc " either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Command "/hold" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change labels or milestones. Authors may only add certain white-listed labels as part of the description such as `kind/*`, `priority/*`, `area/*`, `component/*`, `platform/*`.

**Comment by gardener-botmanager** [comment]
Command "/cc vlerenc " either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Command "/hold" either unknown, wrongly parameterized or not permitted for issue/PR.

**Comment by gardener-botmanager** [comment]
Only code owners are allowed to change assignees. Commenters may only assign or unassign themselves (no args/users permitted).

**Comment by rfranzke** [comment]
/close
foo

**Comment by rfranzke** [comment]
/reopen
because it's still relevant
